* Regular triangulations for Cosmology

Regular triangulations are a very useful tool compute the *geometric
adhesion model*.  This code solves Burgers' equation

\[\frac{\partial u}{\partial t} + (u \cdot \grad)u = \nu \grad^2 u.\]

This equation is solved using geometric methods available in the
Computational Geometry Algorithms Library (CGAL).

** Features
- generate initial conditions
- create glass files
- compute Zeldovich displacements
- compute the adhesion model
- work in 2D or 3D
- output in PLY

*** future 
**** (merge from git:jhidding/adhesion-example repo)
- OBJ triangle output (splits polygons into triangles, but renders better)
- Lloyd iteration glasses
**** Todo
- periodic triangulations
- use HDF5
- increase test coverage

** Output
The output of the 3D adhesion code is in PLY format. PLY is a very liberal specification that
supports storing polygons of any number. Filaments and wall structures are stored in different
files (clusters are stored separately). We associate a density with each element in the PLY file.
This is within specification but not /canon/, so some applications claiming to support PLY
(like paraview) may crash trying to load these files.

** Build
*** Prerequisites
- CGAL >= 4.11
- C++17 compatible compiler (GCC >= 7, LLVM/clang >= 4)
- Meson / ninja build system
- FFTW3
- GNU Scientific Library (GSL)
- (for unit testing only) GTest

*** Building
In the project folder, run ~meson~ and subsequently ~ninja~.
#+BEGIN_SRC sh :eval no
$ meson build --buildtype release
...
$ cd build
build$ ninja
#+END_SRC

To run unit tests (currently only tests PLY output code)

#+BEGIN_SRC sh :eval no
build $ ninja test
#+END_SRC
